version: '3'
services:
  app:
    image: node:lts
    container_name: api
    working_dir: /app
    volumes:
      - ./api:/app
      - ./prisma:/app/prisma
    ports:
      - '34529:34529'
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - db
    network_mode: "host"

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: "host"
      
volumes:
  pgdata:
